[package]
name = "feiyu-desktop"
version = "2.0.0"
description = "一个漂亮得不像实力派的在线视频播放器 ✨"
authors = ["Del.Wang"]
license = "GPL-3.0-only"
repository = "https://github.com/idootop/feiyu-player"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }
tauri-plugin-os = "2"
tauri-plugin-shell = "2"
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
tauri-plugin-cors-fetch = "2.1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
